apiVersion: v1
kind: Service
metadata:
  name: {{ template "platmatic-syslog.fullname" . }}
  labels:
    app: {{ template "platmatic-syslog.fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
spec:
  type: LoadBalancer
  ports:
  - name: syslog-tcp
    port: 9000
    targetPort: 8080
    protocol: TCP
  selector:
    app: {{ template "platmatic-syslog.fullname" . }}